examples/url-parsing/url-parsing.go
Just something I stumbled across parsing an IPv6 address. SplitHostPort should work in all cases where strings.Split("url", ":") works as well as more complicated cases.
=> url-parsing: Use net.SplitHostPort

examples/random-numbers/random-numbers.go
Example shows methods being called on r1 (type Rand) not s1 (type Source).  Fix comment to reflect this correctly.
=> Fix comment on rand example.

templates/example.tmpl, templates/index.tmpl
The html doctype is html5 but the meta charset is not, so make some minor change to prevent some charset detect problem. my Ngnix and Firefox meet this problem.
=> using html5 meta charset tag

tools/format
Based on the comments on [this commit](https://github.com/mmcgrana/gobyexample/commit/8e7a6bb08685033cddff20f626896fd269b403b7) I added conditional `sed` commands since syntax is different among OSs and this wasn't working on Linux, other people might add their own platforms by adding more cases.
=> Per platform 'sed' command to format files to have 4 spaces (darwin and linux supported)

bios.sh, tools/generate.go
This adds a [BIOS script](https://www.mixable.net/docs/bios/) that verifies every PR passes go lint, vet and build commands.
See https://github.com/nzoschke/gobyexample/pull/1 for a demo of the status check passing.
Currently lint and vet ignore the examples folder as examples like variables.go have intentionally verbose code for demonstration purposes.
See https://github.com/nzoschke/gobyexample/pull/2 for changes to examples to make lint and vet happier.
=> BIOS script to check lint, vet and build success

bios.sh
Extend bios.sh to ensure that the there are no changes in
the build-time git repo after `tools/build` has been run.
This ensures that the checked-in .go and .sh sources match
the check-in public/ files.
=> Verify the checked-in build

README.md
I translated Go by Example into Japanese and created a website for it!
Website: http://spinute.org/go-by-example
I want you to add a link to the website in README.
=> add a link to Japanese translation in README.md

examples/variables/variables.go
Instead of `short`, which is a common programming language keyword (representing the `short` data type in many languages), use something random like 'apple'.
When I first read this in the example, I thought it was creating a variable of type `short`. It took me a few seconds to realize that the example was showing the declaration of a string, not a short.
While it may just be me (brain fart), hopefully this change would help prevent confusion when reading about variable declarations, especially when the string's value is a common type (but a type that's not in Go).
If it's not worth it, and we leave totally as is, no worries. Just an idea.
=> Change example text in variables.go

tools/build, tools/test
The tool just runs 'go vet' for now; could do more later (like actually
run the examples and compare to some expected output)
=> Adding a basic sanity testing tool to run during 'build'.

examples/command-line-flags/command-line-flags.sh, examples/command-line-subcommands/command-line-subcommands.sh, public/command-line-flags, public/command-line-subcommands
The command-line-flags page referenced environment variables as the next page in the text, but the actual next page was command-line-subcommands.  This PR just moves that text to the command-line-subcommands page.
=> Fix an incorrect textual reference

.travis.yml, tools/build, tools/generate, tools/generate.go
This is done by routing the generation of HTML into a temporary directory,
and checking its diff agains the existing public/ when running tests.
Fixes #237
=> When testing on Travis, verify that tools/build was run

examples/http-servers/http-servers.go
It says "Here *out* simple response is …", but should say "Here *our* simple response is …".
=> Fix typo in http servers example

.gitattributes
Currently gobyexample is flagged as a CSS repository because of all the
generated HTML.
Following instructions at https://github.com/github/linguist#vendored-code to
ask Github to ignore files that are not actual origin code.
=> Fix up language attribution for the Github UI

CONTRIBUTING.md
#259 demonstrates that contributors can be confused about what to do when encountering Travis errors from comparing the generated site with the checked-in HTML
=> Update CONTRIBUTING guide to mention tools/build

examples/json/json.go
Names without capital letters will be ignored by the JSON Marshaller. This may cause confusion when fields are not being unmarshalled correctly without a warning why.
=> Added warning for capital field names in structs

examples/tickers/tickers.go
The code in the example will leak a goroutine because ticker.Stop() does not close ticker.C.
There is no way to close ticker.C, so `for _ := range ticker` is not a generally safe example for using a ticker.
=> Update tickers.go to not leak goroutine

examples/timeouts/timeouts.go, examples/timeouts/timeouts.hash, examples/timeouts/timeouts.sh, public/timeouts
The buffered channel prevents goroutine leaks in case the
channel doesn't end up being read (as indeed happens to c1).
Updates #207
=> Clarify use of buffered channel in the timeouts example.

examples.txt, examples/testing/main_test.go, examples/testing/main_test.sh, examples/testing/testing.hash, public/command-line-arguments, public/index.html, public/temporary-files-and-directories, public/testing
Note: I opted for using a single-file test in `package main` to make this work with the Go playground. It turns out the playground has a feature wherein a single file that has no `main` but does have `Test*` functions will be treated as a test file and run with `go test`. But the package has to be `main`. I think the example is still clear enough, and the main value here is demonstrating the table-driven style which is idiomatic Go.
=> New example: unit testing

examples/structs/structs.sh, public/structs
Quick fix to the ordering of the example output. It did not match the order that the code was printing in.
=> Structs - fix example output

examples/tickers/tickers.go
Comment says `range` builtin used but `select` is actually used.
=> Fixed comment in tickers.go

README.md
Hello,
The previous maintainers of the `Chinese` documents can no longer maintain the documents in time due to work reasons. 
Now they will be transferred to [gobyexample-cn](https://github.com/gobyexample-cn) maintenance, and the previous maintainers ([xg-wang](https://github.com/xg-wang)) are also in the organization. 
Can you merge this pr, it is a great glory to us, thank you very much.
=> Change chinese translator

README.md
As gobyexample.com.ua going to be dropped soon,
translation moving to github pages hosting.
=> Ukrainian Translation URL changes

examples/regular-expressions/regular-expressions.go
This PR fixes a mistake about constants in `MustCompile` function description.
Solves #325
=> Fix MustCompile comment error

examples/testing/main_test.go
Fail* continues execution, right function probably will be Fatal*.
https://golang.org/pkg/testing/#B.Fail
https://golang.org/pkg/testing/#T.Fatal
=> Change t.Fail to t.Fatal

.travis.yml
This is in line with the Go support policy of current version + previous version
=> Test with both Go 1.17 and 1.16

README.md
For some reason the old badge Markdown stopped working. This updated snippet was pulled from the Travis app and seems to work again.
=> Update Travis badge Markdown per Travis app

examples/goroutines/goroutines.sh, public/goroutines
Clarify comment for the goroutines sample
The current comment may be interpreted to say that the output must be
interleaved, when in fact it doesn't have to be (it depends on the order
the goroutines are run). Make the comment more permissive to avoid the
confusion.
Fixes #365
=> Clarify comment for the goroutines sample

examples/mutexes/mutexes.go
Embedding a mutex is a really bad idea. It exposes the Lock and Unlock methods on the enclosing type, which then allows code from outside your type to mess with your mutex.
There was no reason to embed the mutex in this example. The comment say it is idiomatic to do so, but that is untrue.  Using a mutex called "mu" (unexported) is idiomatic.
=> don't embed the mutex

examples/environment-variables/environment-variables.sh, public/environment-variables
Otherwise readers may think that overridden variables are not listed. The Go documentation only implies this, so let's make it explicit for beginners.
=> Mention that environment variable set by program is also listed by `os.Environ()`

tools/build, tools/build-loop, tools/format, tools/generate, tools/measure, tools/serve, tools/test, tools/upload
Using env to find bash instead of hard coding bash path, [offers better portability](https://stackoverflow.com/questions/16365130/what-is-the-difference-between-usr-bin-env-bash-and-usr-bin-bash).
By using env, the OS looks inside the PATH variable and finds bash, instead of trying to run bash from `/bin/bash` which is not the case for some GNU/Linux distros such as NixOS.
=> /bin/bash -> /usr/bin/env bash

examples/if-else/if-else.sh, public/if-else
Updated if-else.sh to match the code in the if-else example, here is the updated output:
=> typo fix - if-else.sh

examples/strings-and-runes/strings-and-runes.go, examples/strings-and-runes/strings-and-runes.hash, public/strings-and-runes
Found a minor inaccuracy in the write-up for the "Strings and Runes" section: a UTF-8 "code point" can span multiple bytes for a single Thai character; a single Thai character won't span multiple UTF-8 code points because a "UTF-8 code point" is defined as a specific point on the UTF-8 character map, pertaining to a singular, specific character.
=> Fix verbiage for Strings and Runes (noissue)

public/site.css, templates/site.css
This site has been a part of my reference site list for a long time but for me a dark theme user it gets a bit fatiguing so it would be nice to have a simple dark mode. hope it isn't offensive just thought it would be a nice addition.
the colors are based on tokyo_night
=> added: a dark mode in css for us night dwellers

examples/custom-errors/custom-errors.sh, examples/errors/errors.sh, public/custom-errors, public/errors
The shell entry for custom-errors is missing the shell prompt line. Small change, but nice for consistency!
=> Add the shell prompt/command to custom-errors.sh

examples/custom-errors/custom-errors.go, examples/custom-errors/custom-errors.hash, public/custom-errors
`usualy` -> `usually`.
I ran `./tools/build` and some lines were moved.
=> Fix typo in a comment

examples/enums/enums.go, examples/enums/enums.hash, public/enums
Should be `ServerState` instead of `StateType` on [Enums](https://gobyexample.com/enums)
=> Fix typo in the enums example

examples/range-over-iterators/range-over-iterators.sh, public/range-over-iterators
The `range-over-iterators` file does not include the command `go run range-over-iterators.go`, which is inconsistent with the rest of the project. This omission may confuse users, as they won’t know what to name their file or which command to run locally. I have fixed this.
=> Fixed missing command in the range-over-iterators file

examples/http-server/http-server.sh, public/http-server
Fixed the non-existent filename used in the `http-server` example.
=> Fix http-server filename

examples/timers/timers.sh
Replaced Go-style `//` comments with shell-style `#` comments in `examples/timers/timers.sh`. Resolves issue #604
=> Fix incorrect comment style in timers.sh

README.md
• Added link to Italian translation of Go by Example in the Translations section
• Italian translation is available at https://gobyexampleit.andrearaponi.it/
• Added in alphabetical order among existing translations
=> Add Italian translation link to README
